// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKLYGuiBJjlcGq_jSbebRe3HZNj2Nob0g',
    appId: '1:142089123243:web:e7758d096c7e06e1fcceee',
    messagingSenderId: '142089123243',
    projectId: 'melee-notes',
    authDomain: 'melee-notes.firebaseapp.com',
    storageBucket: 'melee-notes.appspot.com',
    measurementId: 'G-2HV8KLR73Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQaaB7MPx67h1YM8ab1xpnGNNmYOjq8Nw',
    appId: '1:142089123243:android:09008015fef792f7fcceee',
    messagingSenderId: '142089123243',
    projectId: 'melee-notes',
    storageBucket: 'melee-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2uyQBnrhlKvO5sUHpS6ahVQj3qV8goNw',
    appId: '1:142089123243:ios:e0334ef58c0e42c6fcceee',
    messagingSenderId: '142089123243',
    projectId: 'melee-notes',
    storageBucket: 'melee-notes.appspot.com',
    iosClientId: '142089123243-ck8v7v35eqnah66848v3k3b2d5poqkr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.meleeNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2uyQBnrhlKvO5sUHpS6ahVQj3qV8goNw',
    appId: '1:142089123243:ios:e0334ef58c0e42c6fcceee',
    messagingSenderId: '142089123243',
    projectId: 'melee-notes',
    storageBucket: 'melee-notes.appspot.com',
    iosClientId: '142089123243-ck8v7v35eqnah66848v3k3b2d5poqkr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.meleeNotes',
  );
}
